sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t joeygibson/debian:jessie .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push joeygibson/debian:jessie 

script:
  - /bin/true

